/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BlackCard from './model/BlackCard';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import Login from './model/Login';
import PasswordChange from './model/PasswordChange';
import PasswordReset from './model/PasswordReset';
import PasswordResetConfirm from './model/PasswordResetConfirm';
import Register from './model/Register';
import UserDetails from './model/UserDetails';
import VerifyEmail from './model/VerifyEmail';
import WhiteCard from './model/WhiteCard';
import ApiApi from './api/ApiApi';
import CardApiApi from './api/CardApiApi';
import RestAuthApi from './api/RestAuthApi';


/**
* Test_description.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SnippetsApi = require('index'); // See note below*.
* var xxxSvc = new SnippetsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SnippetsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SnippetsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SnippetsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BlackCard model constructor.
     * @property {module:model/BlackCard}
     */
    BlackCard,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The Login model constructor.
     * @property {module:model/Login}
     */
    Login,

    /**
     * The PasswordChange model constructor.
     * @property {module:model/PasswordChange}
     */
    PasswordChange,

    /**
     * The PasswordReset model constructor.
     * @property {module:model/PasswordReset}
     */
    PasswordReset,

    /**
     * The PasswordResetConfirm model constructor.
     * @property {module:model/PasswordResetConfirm}
     */
    PasswordResetConfirm,

    /**
     * The Register model constructor.
     * @property {module:model/Register}
     */
    Register,

    /**
     * The UserDetails model constructor.
     * @property {module:model/UserDetails}
     */
    UserDetails,

    /**
     * The VerifyEmail model constructor.
     * @property {module:model/VerifyEmail}
     */
    VerifyEmail,

    /**
     * The WhiteCard model constructor.
     * @property {module:model/WhiteCard}
     */
    WhiteCard,

    /**
    * The ApiApi service constructor.
    * @property {module:api/ApiApi}
    */
    ApiApi,

    /**
    * The CardApiApi service constructor.
    * @property {module:api/CardApiApi}
    */
    CardApiApi,

    /**
    * The RestAuthApi service constructor.
    * @property {module:api/RestAuthApi}
    */
    RestAuthApi
};
