/**
 * fast-cards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastCards);
  }
}(this, function(expect, FastCards) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastCards.CardsAgainstApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CardsAgainstApi', function() {
    describe('createNewGameGameNewPost', function() {
      it('should call createNewGameGameNewPost successfully', function(done) {
        //uncomment below and update the code to test createNewGameGameNewPost
        //instance.createNewGameGameNewPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('joinGameGameJoinPost', function() {
      it('should call joinGameGameJoinPost successfully', function(done) {
        //uncomment below and update the code to test joinGameGameJoinPost
        //instance.joinGameGameJoinPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leaveGameGameLeavePost', function() {
      it('should call leaveGameGameLeavePost successfully', function(done) {
        //uncomment below and update the code to test leaveGameGameLeavePost
        //instance.leaveGameGameLeavePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('refreshGameRefreshGet', function() {
      it('should call refreshGameRefreshGet successfully', function(done) {
        //uncomment below and update the code to test refreshGameRefreshGet
        //instance.refreshGameRefreshGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selectWinnerGameSelectwinnerPost', function() {
      it('should call selectWinnerGameSelectwinnerPost successfully', function(done) {
        //uncomment below and update the code to test selectWinnerGameSelectwinnerPost
        //instance.selectWinnerGameSelectwinnerPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('startGameGameStartGamePost', function() {
      it('should call startGameGameStartGamePost successfully', function(done) {
        //uncomment below and update the code to test startGameGameStartGamePost
        //instance.startGameGameStartGamePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submitCardsGameSubmitPost', function() {
      it('should call submitCardsGameSubmitPost successfully', function(done) {
        //uncomment below and update the code to test submitCardsGameSubmitPost
        //instance.submitCardsGameSubmitPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
