/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CardsAgainstHumanityDjangoApi);
  }
}(this, function(expect, CardsAgainstHumanityDjangoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CardsAgainstHumanityDjangoApi.CardApiApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CardApiApi', function() {
    describe('cardApiBlackCardsList', function() {
      it('should call cardApiBlackCardsList successfully', function(done) {
        //uncomment below and update the code to test cardApiBlackCardsList
        //instance.cardApiBlackCardsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardApiBlackCardsPartialUpdate', function() {
      it('should call cardApiBlackCardsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test cardApiBlackCardsPartialUpdate
        //instance.cardApiBlackCardsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardApiBlackCardsRead', function() {
      it('should call cardApiBlackCardsRead successfully', function(done) {
        //uncomment below and update the code to test cardApiBlackCardsRead
        //instance.cardApiBlackCardsRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardApiBlackCardsUpdate', function() {
      it('should call cardApiBlackCardsUpdate successfully', function(done) {
        //uncomment below and update the code to test cardApiBlackCardsUpdate
        //instance.cardApiBlackCardsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardApiWhiteCardsList', function() {
      it('should call cardApiWhiteCardsList successfully', function(done) {
        //uncomment below and update the code to test cardApiWhiteCardsList
        //instance.cardApiWhiteCardsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardApiWhiteCardsPartialUpdate', function() {
      it('should call cardApiWhiteCardsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test cardApiWhiteCardsPartialUpdate
        //instance.cardApiWhiteCardsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardApiWhiteCardsRead', function() {
      it('should call cardApiWhiteCardsRead successfully', function(done) {
        //uncomment below and update the code to test cardApiWhiteCardsRead
        //instance.cardApiWhiteCardsRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardApiWhiteCardsUpdate', function() {
      it('should call cardApiWhiteCardsUpdate successfully', function(done) {
        //uncomment below and update the code to test cardApiWhiteCardsUpdate
        //instance.cardApiWhiteCardsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
