/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SnippetsApi);
  }
}(this, function(expect, SnippetsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SnippetsApi.RestAuthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RestAuthApi', function() {
    describe('restAuthLoginCreate', function() {
      it('should call restAuthLoginCreate successfully', function(done) {
        //uncomment below and update the code to test restAuthLoginCreate
        //instance.restAuthLoginCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthLogoutCreate', function() {
      it('should call restAuthLogoutCreate successfully', function(done) {
        //uncomment below and update the code to test restAuthLogoutCreate
        //instance.restAuthLogoutCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthLogoutList', function() {
      it('should call restAuthLogoutList successfully', function(done) {
        //uncomment below and update the code to test restAuthLogoutList
        //instance.restAuthLogoutList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthPasswordChangeCreate', function() {
      it('should call restAuthPasswordChangeCreate successfully', function(done) {
        //uncomment below and update the code to test restAuthPasswordChangeCreate
        //instance.restAuthPasswordChangeCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthPasswordResetConfirmCreate', function() {
      it('should call restAuthPasswordResetConfirmCreate successfully', function(done) {
        //uncomment below and update the code to test restAuthPasswordResetConfirmCreate
        //instance.restAuthPasswordResetConfirmCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthPasswordResetCreate', function() {
      it('should call restAuthPasswordResetCreate successfully', function(done) {
        //uncomment below and update the code to test restAuthPasswordResetCreate
        //instance.restAuthPasswordResetCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthRegistrationCreate', function() {
      it('should call restAuthRegistrationCreate successfully', function(done) {
        //uncomment below and update the code to test restAuthRegistrationCreate
        //instance.restAuthRegistrationCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthRegistrationVerifyEmailCreate', function() {
      it('should call restAuthRegistrationVerifyEmailCreate successfully', function(done) {
        //uncomment below and update the code to test restAuthRegistrationVerifyEmailCreate
        //instance.restAuthRegistrationVerifyEmailCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthUserPartialUpdate', function() {
      it('should call restAuthUserPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test restAuthUserPartialUpdate
        //instance.restAuthUserPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthUserRead', function() {
      it('should call restAuthUserRead successfully', function(done) {
        //uncomment below and update the code to test restAuthUserRead
        //instance.restAuthUserRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restAuthUserUpdate', function() {
      it('should call restAuthUserUpdate successfully', function(done) {
        //uncomment below and update the code to test restAuthUserUpdate
        //instance.restAuthUserUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
