/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlackCard model module.
 * @module model/BlackCard
 * @version v1
 */
class BlackCard {
    /**
     * Constructs a new <code>BlackCard</code>.
     * @alias module:model/BlackCard
     * @param text {String} 
     * @param icon {String} 
     * @param deck {String} 
     * @param pick {Number} 
     */
    constructor(text, icon, deck, pick) { 
        
        BlackCard.initialize(this, text, icon, deck, pick);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, text, icon, deck, pick) { 
        obj['text'] = text;
        obj['icon'] = icon;
        obj['deck'] = deck;
        obj['pick'] = pick;
    }

    /**
     * Constructs a <code>BlackCard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlackCard} obj Optional instance to populate.
     * @return {module:model/BlackCard} The populated <code>BlackCard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlackCard();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('deck')) {
                obj['deck'] = ApiClient.convertToType(data['deck'], 'String');
            }
            if (data.hasOwnProperty('pick')) {
                obj['pick'] = ApiClient.convertToType(data['pick'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} text
 */
BlackCard.prototype['text'] = undefined;

/**
 * @member {String} icon
 */
BlackCard.prototype['icon'] = undefined;

/**
 * @member {String} deck
 */
BlackCard.prototype['deck'] = undefined;

/**
 * @member {Number} pick
 */
BlackCard.prototype['pick'] = undefined;






export default BlackCard;

