/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CardSubmission model module.
 * @module model/CardSubmission
 * @version v1
 */
class CardSubmission {
    /**
     * Constructs a new <code>CardSubmission</code>.
     * @alias module:model/CardSubmission
     */
    constructor() { 
        
        CardSubmission.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CardSubmission</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardSubmission} obj Optional instance to populate.
     * @return {module:model/CardSubmission} The populated <code>CardSubmission</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardSubmission();

            if (data.hasOwnProperty('submitted_white_cards')) {
                obj['submitted_white_cards'] = ApiClient.convertToType(data['submitted_white_cards'], ['String']);
            }
            if (data.hasOwnProperty('submission_id')) {
                obj['submission_id'] = ApiClient.convertToType(data['submission_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} submitted_white_cards
 */
CardSubmission.prototype['submitted_white_cards'] = undefined;

/**
 * @member {Number} submission_id
 */
CardSubmission.prototype['submission_id'] = undefined;






export default CardSubmission;

