/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Profile from './Profile';
import WhiteCard from './WhiteCard';

/**
 * The GameRoundProfileData model module.
 * @module model/GameRoundProfileData
 * @version v1
 */
class GameRoundProfileData {
    /**
     * Constructs a new <code>GameRoundProfileData</code>.
     * @alias module:model/GameRoundProfileData
     * @param currentPoints {Number} 
     */
    constructor(currentPoints) { 
        
        GameRoundProfileData.initialize(this, currentPoints);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentPoints) { 
        obj['current_points'] = currentPoints;
    }

    /**
     * Constructs a <code>GameRoundProfileData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameRoundProfileData} obj Optional instance to populate.
     * @return {module:model/GameRoundProfileData} The populated <code>GameRoundProfileData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameRoundProfileData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('round')) {
                obj['round'] = ApiClient.convertToType(data['round'], 'String');
            }
            if (data.hasOwnProperty('user_profile')) {
                obj['user_profile'] = Profile.constructFromObject(data['user_profile']);
            }
            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], [WhiteCard]);
            }
            if (data.hasOwnProperty('current_points')) {
                obj['current_points'] = ApiClient.convertToType(data['current_points'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GameRoundProfileData.prototype['id'] = undefined;

/**
 * @member {String} round
 */
GameRoundProfileData.prototype['round'] = undefined;

/**
 * @member {module:model/Profile} user_profile
 */
GameRoundProfileData.prototype['user_profile'] = undefined;

/**
 * @member {Array.<module:model/WhiteCard>} cards
 */
GameRoundProfileData.prototype['cards'] = undefined;

/**
 * @member {Number} current_points
 */
GameRoundProfileData.prototype['current_points'] = undefined;






export default GameRoundProfileData;

