/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlackCard from './BlackCard';
import GameRoundWinner from './GameRoundWinner';
import GameSession from './GameSession';
import Profile from './Profile';

/**
 * The GameRound model module.
 * @module model/GameRound
 * @version v1
 */
class GameRound {
    /**
     * Constructs a new <code>GameRound</code>.
     * @alias module:model/GameRound
     * @param roundNumber {Number} 
     */
    constructor(roundNumber) { 
        
        GameRound.initialize(this, roundNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, roundNumber) { 
        obj['roundNumber'] = roundNumber;
    }

    /**
     * Constructs a <code>GameRound</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameRound} obj Optional instance to populate.
     * @return {module:model/GameRound} The populated <code>GameRound</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameRound();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('session')) {
                obj['session'] = GameSession.constructFromObject(data['session']);
            }
            if (data.hasOwnProperty('tzar')) {
                obj['tzar'] = Profile.constructFromObject(data['tzar']);
            }
            if (data.hasOwnProperty('active_black_card')) {
                obj['active_black_card'] = BlackCard.constructFromObject(data['active_black_card']);
            }
            if (data.hasOwnProperty('roundNumber')) {
                obj['roundNumber'] = ApiClient.convertToType(data['roundNumber'], 'Number');
            }
            if (data.hasOwnProperty('winner')) {
                obj['winner'] = GameRoundWinner.constructFromObject(data['winner']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GameRound.prototype['id'] = undefined;

/**
 * @member {module:model/GameSession} session
 */
GameRound.prototype['session'] = undefined;

/**
 * @member {module:model/Profile} tzar
 */
GameRound.prototype['tzar'] = undefined;

/**
 * @member {module:model/BlackCard} active_black_card
 */
GameRound.prototype['active_black_card'] = undefined;

/**
 * @member {Number} roundNumber
 */
GameRound.prototype['roundNumber'] = undefined;

/**
 * @member {module:model/GameRoundWinner} winner
 */
GameRound.prototype['winner'] = undefined;






export default GameRound;

