/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GameSession model module.
 * @module model/GameSession
 * @version v1
 */
class GameSession {
    /**
     * Constructs a new <code>GameSession</code>.
     * @alias module:model/GameSession
     * @param sessionId {String} 
     */
    constructor(sessionId) { 
        
        GameSession.initialize(this, sessionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sessionId) { 
        obj['session_id'] = sessionId;
    }

    /**
     * Constructs a <code>GameSession</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameSession} obj Optional instance to populate.
     * @return {module:model/GameSession} The populated <code>GameSession</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameSession();

            if (data.hasOwnProperty('session_id')) {
                obj['session_id'] = ApiClient.convertToType(data['session_id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('has_started')) {
                obj['has_started'] = ApiClient.convertToType(data['has_started'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} session_id
 */
GameSession.prototype['session_id'] = undefined;

/**
 * @member {Date} created_at
 */
GameSession.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
GameSession.prototype['updated_at'] = undefined;

/**
 * @member {Boolean} has_started
 */
GameSession.prototype['has_started'] = undefined;






export default GameSession;

