/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GameRoundWinnerUser from './GameRoundWinnerUser';

/**
 * The GameRoundWinner model module.
 * @module model/GameRoundWinner
 * @version v1
 */
class GameRoundWinner {
    /**
     * Constructs a new <code>GameRoundWinner</code>.
     * @alias module:model/GameRoundWinner
     */
    constructor() { 
        
        GameRoundWinner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameRoundWinner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameRoundWinner} obj Optional instance to populate.
     * @return {module:model/GameRoundWinner} The populated <code>GameRoundWinner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameRoundWinner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = GameRoundWinnerUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GameRoundWinner.prototype['id'] = undefined;

/**
 * @member {String} bio
 */
GameRoundWinner.prototype['bio'] = undefined;

/**
 * @member {String} avatar
 */
GameRoundWinner.prototype['avatar'] = undefined;

/**
 * @member {module:model/GameRoundWinnerUser} user
 */
GameRoundWinner.prototype['user'] = undefined;






export default GameRoundWinner;

