/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GameRoundWinnerUserContentType model module.
 * @module model/GameRoundWinnerUserContentType
 * @version v1
 */
class GameRoundWinnerUserContentType {
    /**
     * Constructs a new <code>GameRoundWinnerUserContentType</code>.
     * @alias module:model/GameRoundWinnerUserContentType
     * @param appLabel {String} 
     * @param model {String} 
     */
    constructor(appLabel, model) { 
        
        GameRoundWinnerUserContentType.initialize(this, appLabel, model);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appLabel, model) { 
        obj['app_label'] = appLabel;
        obj['model'] = model;
    }

    /**
     * Constructs a <code>GameRoundWinnerUserContentType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameRoundWinnerUserContentType} obj Optional instance to populate.
     * @return {module:model/GameRoundWinnerUserContentType} The populated <code>GameRoundWinnerUserContentType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameRoundWinnerUserContentType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('app_label')) {
                obj['app_label'] = ApiClient.convertToType(data['app_label'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GameRoundWinnerUserContentType.prototype['id'] = undefined;

/**
 * @member {String} app_label
 */
GameRoundWinnerUserContentType.prototype['app_label'] = undefined;

/**
 * @member {String} model
 */
GameRoundWinnerUserContentType.prototype['model'] = undefined;






export default GameRoundWinnerUserContentType;

