/**
 * fast-cards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlackCard from './BlackCard';
import CardsAgainstHumanityPlayer from './CardsAgainstHumanityPlayer';
import LastWinnerInfo from './LastWinnerInfo';
import PlayerOutsideView from './PlayerOutsideView';
import Submission from './Submission';

/**
 * The GameStatePlayerView model module.
 * @module model/GameStatePlayerView
 * @version 0.2.0
 */
class GameStatePlayerView {
    /**
     * Constructs a new <code>GameStatePlayerView</code>.
     * @alias module:model/GameStatePlayerView
     * @param player {module:model/CardsAgainstHumanityPlayer} 
     * @param roomName {String} 
     * @param state {String} 
     * @param roundCount {Number} 
     * @param otherPlayers {Array.<module:model/PlayerOutsideView>} 
     */
    constructor(player, roomName, state, roundCount, otherPlayers) { 
        
        GameStatePlayerView.initialize(this, player, roomName, state, roundCount, otherPlayers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, player, roomName, state, roundCount, otherPlayers) { 
        obj['player'] = player;
        obj['room_name'] = roomName;
        obj['state'] = state;
        obj['round_count'] = roundCount;
        obj['other_players'] = otherPlayers;
    }

    /**
     * Constructs a <code>GameStatePlayerView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameStatePlayerView} obj Optional instance to populate.
     * @return {module:model/GameStatePlayerView} The populated <code>GameStatePlayerView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameStatePlayerView();

            if (data.hasOwnProperty('player')) {
                obj['player'] = CardsAgainstHumanityPlayer.constructFromObject(data['player']);
            }
            if (data.hasOwnProperty('room_name')) {
                obj['room_name'] = ApiClient.convertToType(data['room_name'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('round_count')) {
                obj['round_count'] = ApiClient.convertToType(data['round_count'], 'Number');
            }
            if (data.hasOwnProperty('currently_active_card')) {
                obj['currently_active_card'] = BlackCard.constructFromObject(data['currently_active_card']);
            }
            if (data.hasOwnProperty('player_submissions')) {
                obj['player_submissions'] = ApiClient.convertToType(data['player_submissions'], {'String': Submission});
            }
            if (data.hasOwnProperty('other_players')) {
                obj['other_players'] = ApiClient.convertToType(data['other_players'], [PlayerOutsideView]);
            }
            if (data.hasOwnProperty('last_winners')) {
                obj['last_winners'] = ApiClient.convertToType(data['last_winners'], [LastWinnerInfo]);
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CardsAgainstHumanityPlayer} player
 */
GameStatePlayerView.prototype['player'] = undefined;

/**
 * @member {String} room_name
 */
GameStatePlayerView.prototype['room_name'] = undefined;

/**
 * @member {String} state
 */
GameStatePlayerView.prototype['state'] = undefined;

/**
 * @member {Number} round_count
 */
GameStatePlayerView.prototype['round_count'] = undefined;

/**
 * @member {module:model/BlackCard} currently_active_card
 */
GameStatePlayerView.prototype['currently_active_card'] = undefined;

/**
 * @member {Object.<String, module:model/Submission>} player_submissions
 */
GameStatePlayerView.prototype['player_submissions'] = undefined;

/**
 * @member {Array.<module:model/PlayerOutsideView>} other_players
 */
GameStatePlayerView.prototype['other_players'] = undefined;

/**
 * @member {Array.<module:model/LastWinnerInfo>} last_winners
 */
GameStatePlayerView.prototype['last_winners'] = undefined;

/**
 * @member {String} mode
 * @default 'NORMAL'
 */
GameStatePlayerView.prototype['mode'] = 'NORMAL';






export default GameStatePlayerView;

