/**
 * fast-cards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Submission from './Submission';

/**
 * The LastWinnerInfo model module.
 * @module model/LastWinnerInfo
 * @version 0.1.0
 */
class LastWinnerInfo {
    /**
     * Constructs a new <code>LastWinnerInfo</code>.
     * @alias module:model/LastWinnerInfo
     * @param username {String} 
     * @param submission {module:model/Submission} 
     */
    constructor(username, submission) { 
        
        LastWinnerInfo.initialize(this, username, submission);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, submission) { 
        obj['username'] = username;
        obj['submission'] = submission;
    }

    /**
     * Constructs a <code>LastWinnerInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LastWinnerInfo} obj Optional instance to populate.
     * @return {module:model/LastWinnerInfo} The populated <code>LastWinnerInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LastWinnerInfo();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('submission')) {
                obj['submission'] = Submission.constructFromObject(data['submission']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
LastWinnerInfo.prototype['username'] = undefined;

/**
 * @member {module:model/Submission} submission
 */
LastWinnerInfo.prototype['submission'] = undefined;






export default LastWinnerInfo;

