/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PasswordResetConfirm model module.
 * @module model/PasswordResetConfirm
 * @version v1
 */
class PasswordResetConfirm {
    /**
     * Constructs a new <code>PasswordResetConfirm</code>.
     * @alias module:model/PasswordResetConfirm
     * @param newPassword1 {String} 
     * @param newPassword2 {String} 
     * @param uid {String} 
     * @param token {String} 
     */
    constructor(newPassword1, newPassword2, uid, token) { 
        
        PasswordResetConfirm.initialize(this, newPassword1, newPassword2, uid, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, newPassword1, newPassword2, uid, token) { 
        obj['new_password1'] = newPassword1;
        obj['new_password2'] = newPassword2;
        obj['uid'] = uid;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>PasswordResetConfirm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PasswordResetConfirm} obj Optional instance to populate.
     * @return {module:model/PasswordResetConfirm} The populated <code>PasswordResetConfirm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PasswordResetConfirm();

            if (data.hasOwnProperty('new_password1')) {
                obj['new_password1'] = ApiClient.convertToType(data['new_password1'], 'String');
            }
            if (data.hasOwnProperty('new_password2')) {
                obj['new_password2'] = ApiClient.convertToType(data['new_password2'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} new_password1
 */
PasswordResetConfirm.prototype['new_password1'] = undefined;

/**
 * @member {String} new_password2
 */
PasswordResetConfirm.prototype['new_password2'] = undefined;

/**
 * @member {String} uid
 */
PasswordResetConfirm.prototype['uid'] = undefined;

/**
 * @member {String} token
 */
PasswordResetConfirm.prototype['token'] = undefined;






export default PasswordResetConfirm;

