/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PasswordChange model module.
 * @module model/PasswordChange
 * @version v1
 */
class PasswordChange {
    /**
     * Constructs a new <code>PasswordChange</code>.
     * @alias module:model/PasswordChange
     * @param newPassword1 {String} 
     * @param newPassword2 {String} 
     */
    constructor(newPassword1, newPassword2) { 
        
        PasswordChange.initialize(this, newPassword1, newPassword2);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, newPassword1, newPassword2) { 
        obj['new_password1'] = newPassword1;
        obj['new_password2'] = newPassword2;
    }

    /**
     * Constructs a <code>PasswordChange</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PasswordChange} obj Optional instance to populate.
     * @return {module:model/PasswordChange} The populated <code>PasswordChange</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PasswordChange();

            if (data.hasOwnProperty('new_password1')) {
                obj['new_password1'] = ApiClient.convertToType(data['new_password1'], 'String');
            }
            if (data.hasOwnProperty('new_password2')) {
                obj['new_password2'] = ApiClient.convertToType(data['new_password2'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} new_password1
 */
PasswordChange.prototype['new_password1'] = undefined;

/**
 * @member {String} new_password2
 */
PasswordChange.prototype['new_password2'] = undefined;






export default PasswordChange;

