/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Register model module.
 * @module model/Register
 * @version v1
 */
class Register {
    /**
     * Constructs a new <code>Register</code>.
     * @alias module:model/Register
     * @param username {String} 
     * @param email {String} 
     * @param password1 {String} 
     * @param password2 {String} 
     */
    constructor(username, email, password1, password2) { 
        
        Register.initialize(this, username, email, password1, password2);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, email, password1, password2) { 
        obj['username'] = username;
        obj['email'] = email;
        obj['password1'] = password1;
        obj['password2'] = password2;
    }

    /**
     * Constructs a <code>Register</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Register} obj Optional instance to populate.
     * @return {module:model/Register} The populated <code>Register</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Register();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password1')) {
                obj['password1'] = ApiClient.convertToType(data['password1'], 'String');
            }
            if (data.hasOwnProperty('password2')) {
                obj['password2'] = ApiClient.convertToType(data['password2'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
Register.prototype['username'] = undefined;

/**
 * @member {String} email
 */
Register.prototype['email'] = undefined;

/**
 * @member {String} password1
 */
Register.prototype['password1'] = undefined;

/**
 * @member {String} password2
 */
Register.prototype['password2'] = undefined;






export default Register;

