/**
 * fast-cards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Room from './Room';

/**
 * The RoomListing model module.
 * @module model/RoomListing
 * @version 0.2.0
 */
class RoomListing {
    /**
     * Constructs a new <code>RoomListing</code>.
     * @alias module:model/RoomListing
     * @param rooms {Array.<module:model/Room>} 
     */
    constructor(rooms) { 
        
        RoomListing.initialize(this, rooms);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rooms) { 
        obj['rooms'] = rooms;
    }

    /**
     * Constructs a <code>RoomListing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RoomListing} obj Optional instance to populate.
     * @return {module:model/RoomListing} The populated <code>RoomListing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RoomListing();

            if (data.hasOwnProperty('rooms')) {
                obj['rooms'] = ApiClient.convertToType(data['rooms'], [Room]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Room>} rooms
 */
RoomListing.prototype['rooms'] = undefined;






export default RoomListing;

