/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubmittedCardRequest model module.
 * @module model/SubmittedCardRequest
 * @version v1
 */
class SubmittedCardRequest {
    /**
     * Constructs a new <code>SubmittedCardRequest</code>.
     * @alias module:model/SubmittedCardRequest
     * @param submissionText {String} 
     */
    constructor(submissionText) { 
        
        SubmittedCardRequest.initialize(this, submissionText);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, submissionText) { 
        obj['submission_text'] = submissionText;
    }

    /**
     * Constructs a <code>SubmittedCardRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubmittedCardRequest} obj Optional instance to populate.
     * @return {module:model/SubmittedCardRequest} The populated <code>SubmittedCardRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubmittedCardRequest();

            if (data.hasOwnProperty('submission_text')) {
                obj['submission_text'] = ApiClient.convertToType(data['submission_text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} submission_text
 */
SubmittedCardRequest.prototype['submission_text'] = undefined;






export default SubmittedCardRequest;

