/**
 * fast-cards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserLoginSchema model module.
 * @module model/UserLoginSchema
 * @version 0.0.1
 */
class UserLoginSchema {
    /**
     * Constructs a new <code>UserLoginSchema</code>.
     * @alias module:model/UserLoginSchema
     * @param email {String} 
     * @param password {String} 
     */
    constructor(email, password) { 
        
        UserLoginSchema.initialize(this, email, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, password) { 
        obj['email'] = email;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>UserLoginSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserLoginSchema} obj Optional instance to populate.
     * @return {module:model/UserLoginSchema} The populated <code>UserLoginSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserLoginSchema();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
UserLoginSchema.prototype['email'] = undefined;

/**
 * @member {String} password
 */
UserLoginSchema.prototype['password'] = undefined;






export default UserLoginSchema;

