/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserDetails model module.
 * @module model/UserDetails
 * @version v1
 */
class UserDetails {
    /**
     * Constructs a new <code>UserDetails</code>.
     * @alias module:model/UserDetails
     * @param username {String} Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    constructor(username) { 
        
        UserDetails.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>UserDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserDetails} obj Optional instance to populate.
     * @return {module:model/UserDetails} The populated <code>UserDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDetails();

            if (data.hasOwnProperty('pk')) {
                obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} pk
 */
UserDetails.prototype['pk'] = undefined;

/**
 * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
 * @member {String} username
 */
UserDetails.prototype['username'] = undefined;

/**
 * @member {String} email
 */
UserDetails.prototype['email'] = undefined;

/**
 * @member {String} first_name
 */
UserDetails.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
UserDetails.prototype['last_name'] = undefined;






export default UserDetails;

