/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Login from '../model/Login';
import PasswordChange from '../model/PasswordChange';
import PasswordReset from '../model/PasswordReset';
import PasswordResetConfirm from '../model/PasswordResetConfirm';
import Register from '../model/Register';
import UserDetails from '../model/UserDetails';
import VerifyEmail from '../model/VerifyEmail';

/**
* Api service.
* @module api/ApiApi
* @version v1
*/
export default class ApiApi {

    /**
    * Constructs a new ApiApi. 
    * @alias module:api/ApiApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiRestAuthLoginCreate operation.
     * @callback module:api/ApiApi~apiRestAuthLoginCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Login} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check the credentials and return the REST Token if the credentials are valid and authenticated. Calls Django Auth login method to register User ID in Django session framework  Accept the following POST parameters: username, password Return the REST Framework Token Object's key.
     * @param {module:model/Login} data 
     * @param {module:api/ApiApi~apiRestAuthLoginCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Login}
     */
    apiRestAuthLoginCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling apiRestAuthLoginCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Login;
      return this.apiClient.callApi(
        '/api/rest-auth/login/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthLogoutCreate operation.
     * @callback module:api/ApiApi~apiRestAuthLogoutCreateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Calls Django logout method and delete the Token object assigned to the current User object.
     * Accepts/Returns nothing.
     * @param {module:api/ApiApi~apiRestAuthLogoutCreateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiRestAuthLogoutCreate(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/rest-auth/logout/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthLogoutList operation.
     * @callback module:api/ApiApi~apiRestAuthLogoutListCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Calls Django logout method and delete the Token object assigned to the current User object.
     * Accepts/Returns nothing.
     * @param {module:api/ApiApi~apiRestAuthLogoutListCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiRestAuthLogoutList(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/rest-auth/logout/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthPasswordChangeCreate operation.
     * @callback module:api/ApiApi~apiRestAuthPasswordChangeCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PasswordChange} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Calls Django Auth SetPasswordForm save method.
     * Accepts the following POST parameters: new_password1, new_password2 Returns the success/fail message.
     * @param {module:model/PasswordChange} data 
     * @param {module:api/ApiApi~apiRestAuthPasswordChangeCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PasswordChange}
     */
    apiRestAuthPasswordChangeCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling apiRestAuthPasswordChangeCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PasswordChange;
      return this.apiClient.callApi(
        '/api/rest-auth/password/change/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthPasswordResetConfirmCreate operation.
     * @callback module:api/ApiApi~apiRestAuthPasswordResetConfirmCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PasswordResetConfirm} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Password reset e-mail link is confirmed, therefore this resets the user's password.
     * Accepts the following POST parameters: token, uid,     new_password1, new_password2 Returns the success/fail message.
     * @param {module:model/PasswordResetConfirm} data 
     * @param {module:api/ApiApi~apiRestAuthPasswordResetConfirmCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PasswordResetConfirm}
     */
    apiRestAuthPasswordResetConfirmCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling apiRestAuthPasswordResetConfirmCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PasswordResetConfirm;
      return this.apiClient.callApi(
        '/api/rest-auth/password/reset/confirm/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthPasswordResetCreate operation.
     * @callback module:api/ApiApi~apiRestAuthPasswordResetCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PasswordReset} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Calls Django Auth PasswordResetForm save method.
     * Accepts the following POST parameters: email Returns the success/fail message.
     * @param {module:model/PasswordReset} data 
     * @param {module:api/ApiApi~apiRestAuthPasswordResetCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PasswordReset}
     */
    apiRestAuthPasswordResetCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling apiRestAuthPasswordResetCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PasswordReset;
      return this.apiClient.callApi(
        '/api/rest-auth/password/reset/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthRegistrationCreate operation.
     * @callback module:api/ApiApi~apiRestAuthRegistrationCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Register} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/Register} data 
     * @param {module:api/ApiApi~apiRestAuthRegistrationCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Register}
     */
    apiRestAuthRegistrationCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling apiRestAuthRegistrationCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Register;
      return this.apiClient.callApi(
        '/api/rest-auth/registration/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthRegistrationVerifyEmailCreate operation.
     * @callback module:api/ApiApi~apiRestAuthRegistrationVerifyEmailCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VerifyEmail} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/VerifyEmail} data 
     * @param {module:api/ApiApi~apiRestAuthRegistrationVerifyEmailCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VerifyEmail}
     */
    apiRestAuthRegistrationVerifyEmailCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling apiRestAuthRegistrationVerifyEmailCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = VerifyEmail;
      return this.apiClient.callApi(
        '/api/rest-auth/registration/verify-email/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthUserPartialUpdate operation.
     * @callback module:api/ApiApi~apiRestAuthUserPartialUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserDetails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Reads and updates UserModel fields Accepts GET, PUT, PATCH methods.
     * Default accepted fields: username, first_name, last_name Default display fields: pk, username, email, first_name, last_name Read-only fields: pk, email  Returns UserModel fields.
     * @param {module:model/UserDetails} data 
     * @param {module:api/ApiApi~apiRestAuthUserPartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserDetails}
     */
    apiRestAuthUserPartialUpdate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling apiRestAuthUserPartialUpdate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserDetails;
      return this.apiClient.callApi(
        '/api/rest-auth/user/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthUserRead operation.
     * @callback module:api/ApiApi~apiRestAuthUserReadCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserDetails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Reads and updates UserModel fields Accepts GET, PUT, PATCH methods.
     * Default accepted fields: username, first_name, last_name Default display fields: pk, username, email, first_name, last_name Read-only fields: pk, email  Returns UserModel fields.
     * @param {module:api/ApiApi~apiRestAuthUserReadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserDetails}
     */
    apiRestAuthUserRead(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UserDetails;
      return this.apiClient.callApi(
        '/api/rest-auth/user/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiRestAuthUserUpdate operation.
     * @callback module:api/ApiApi~apiRestAuthUserUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserDetails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Reads and updates UserModel fields Accepts GET, PUT, PATCH methods.
     * Default accepted fields: username, first_name, last_name Default display fields: pk, username, email, first_name, last_name Read-only fields: pk, email  Returns UserModel fields.
     * @param {module:model/UserDetails} data 
     * @param {module:api/ApiApi~apiRestAuthUserUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserDetails}
     */
    apiRestAuthUserUpdate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling apiRestAuthUserUpdate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserDetails;
      return this.apiClient.callApi(
        '/api/rest-auth/user/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
