/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GameRoundProfileData from '../model/GameRoundProfileData';
import GameSession from '../model/GameSession';
import InlineResponse2002 from '../model/InlineResponse2002';
import InlineResponse2003 from '../model/InlineResponse2003';
import InlineResponse2004 from '../model/InlineResponse2004';
import InlineResponse2005 from '../model/InlineResponse2005';
import InlineResponse2006 from '../model/InlineResponse2006';
import Profile from '../model/Profile';

/**
* GameEngineApi service.
* @module api/GameEngineApiApi
* @version v1
*/
export default class GameEngineApiApi {

    /**
    * Constructs a new GameEngineApiApi. 
    * @alias module:api/GameEngineApiApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the gameEngineApiGameroundprofiledataCreate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameRoundProfileData} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/GameRoundProfileData} data 
     * @param {module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameRoundProfileData}
     */
    gameEngineApiGameroundprofiledataCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling gameEngineApiGameroundprofiledataCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GameRoundProfileData;
      return this.apiClient.callApi(
        '/game_engine_api/gameroundprofiledata/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiGameroundprofiledataList operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page A page number within the paginated result set.
     * @param {module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2002}
     */
    gameEngineApiGameroundprofiledataList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;
      return this.apiClient.callApi(
        '/game_engine_api/gameroundprofiledata/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiGameroundprofiledataPartialUpdate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataPartialUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameRoundProfileData} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this game round profile data.
     * @param {module:model/GameRoundProfileData} data 
     * @param {module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataPartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameRoundProfileData}
     */
    gameEngineApiGameroundprofiledataPartialUpdate(id, data, callback) {
      let postBody = data;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling gameEngineApiGameroundprofiledataPartialUpdate");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling gameEngineApiGameroundprofiledataPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GameRoundProfileData;
      return this.apiClient.callApi(
        '/game_engine_api/gameroundprofiledata/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiGameroundprofiledataRead operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataReadCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameRoundProfileData} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this game round profile data.
     * @param {module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataReadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameRoundProfileData}
     */
    gameEngineApiGameroundprofiledataRead(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling gameEngineApiGameroundprofiledataRead");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GameRoundProfileData;
      return this.apiClient.callApi(
        '/game_engine_api/gameroundprofiledata/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiGameroundprofiledataUpdate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameRoundProfileData} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this game round profile data.
     * @param {module:model/GameRoundProfileData} data 
     * @param {module:api/GameEngineApiApi~gameEngineApiGameroundprofiledataUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameRoundProfileData}
     */
    gameEngineApiGameroundprofiledataUpdate(id, data, callback) {
      let postBody = data;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling gameEngineApiGameroundprofiledataUpdate");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling gameEngineApiGameroundprofiledataUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GameRoundProfileData;
      return this.apiClient.callApi(
        '/game_engine_api/gameroundprofiledata/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiProfilesList operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiProfilesListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.search A search term.
     * @param {Number} opts.page A page number within the paginated result set.
     * @param {module:api/GameEngineApiApi~gameEngineApiProfilesListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    gameEngineApiProfilesList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2003;
      return this.apiClient.callApi(
        '/game_engine_api/profiles/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiProfilesPartialUpdate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiProfilesPartialUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Profile} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this profile.
     * @param {module:model/Profile} data 
     * @param {module:api/GameEngineApiApi~gameEngineApiProfilesPartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Profile}
     */
    gameEngineApiProfilesPartialUpdate(id, data, callback) {
      let postBody = data;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling gameEngineApiProfilesPartialUpdate");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling gameEngineApiProfilesPartialUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Profile;
      return this.apiClient.callApi(
        '/game_engine_api/profiles/{id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiProfilesRead operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiProfilesReadCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Profile} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this profile.
     * @param {module:api/GameEngineApiApi~gameEngineApiProfilesReadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Profile}
     */
    gameEngineApiProfilesRead(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling gameEngineApiProfilesRead");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Profile;
      return this.apiClient.callApi(
        '/game_engine_api/profiles/{id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiProfilesUpdate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiProfilesUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Profile} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id A unique integer value identifying this profile.
     * @param {module:model/Profile} data 
     * @param {module:api/GameEngineApiApi~gameEngineApiProfilesUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Profile}
     */
    gameEngineApiProfilesUpdate(id, data, callback) {
      let postBody = data;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling gameEngineApiProfilesUpdate");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling gameEngineApiProfilesUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Profile;
      return this.apiClient.callApi(
        '/game_engine_api/profiles/{id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionOpsDelete operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionOpsDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId 
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionOpsDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    gameEngineApiSessionOpsDelete(sessionId, callback) {
      let postBody = null;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionOpsDelete");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/game_engine_api/session/{session_id}/ops/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionOpsList operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionOpsListCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId 
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionOpsListCallback} callback The callback function, accepting three arguments: error, data, response
     */
    gameEngineApiSessionOpsList(sessionId, callback) {
      let postBody = null;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionOpsList");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/game_engine_api/session/{session_id}/ops/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionOpsUpdate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionOpsUpdateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId 
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionOpsUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    gameEngineApiSessionOpsUpdate(sessionId, callback) {
      let postBody = null;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionOpsUpdate");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/game_engine_api/session/{session_id}/ops/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionProfilesList operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionProfilesListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page A page number within the paginated result set.
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionProfilesListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2002}
     */
    gameEngineApiSessionProfilesList(sessionId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionProfilesList");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;
      return this.apiClient.callApi(
        '/game_engine_api/session/{session_id}/profiles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionRoundsList operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionRoundsListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2004} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page A page number within the paginated result set.
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionRoundsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2004}
     */
    gameEngineApiSessionRoundsList(sessionId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionRoundsList");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2004;
      return this.apiClient.callApi(
        '/game_engine_api/session/{session_id}/rounds', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionSubmissionsList operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionSubmissionsListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2005} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page A page number within the paginated result set.
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionSubmissionsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2005}
     */
    gameEngineApiSessionSubmissionsList(sessionId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionSubmissionsList");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2005;
      return this.apiClient.callApi(
        '/game_engine_api/session/{session_id}/submissions/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionViewList operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionViewListCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId 
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionViewListCallback} callback The callback function, accepting three arguments: error, data, response
     */
    gameEngineApiSessionViewList(sessionId, callback) {
      let postBody = null;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionViewList");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/game_engine_api/session/{session_id}/view', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionsCreate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionsCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameSession} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/GameSession} data 
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionsCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameSession}
     */
    gameEngineApiSessionsCreate(data, callback) {
      let postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling gameEngineApiSessionsCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GameSession;
      return this.apiClient.callApi(
        '/game_engine_api/sessions/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionsList operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionsListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2006} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.search A search term.
     * @param {Number} opts.page A page number within the paginated result set.
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2006}
     */
    gameEngineApiSessionsList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search'],
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2006;
      return this.apiClient.callApi(
        '/game_engine_api/sessions/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionsPartialUpdate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionsPartialUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameSession} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId A unique value identifying this game session.
     * @param {module:model/GameSession} data 
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionsPartialUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameSession}
     */
    gameEngineApiSessionsPartialUpdate(sessionId, data, callback) {
      let postBody = data;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionsPartialUpdate");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling gameEngineApiSessionsPartialUpdate");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GameSession;
      return this.apiClient.callApi(
        '/game_engine_api/sessions/{session_id}/', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionsRead operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionsReadCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameSession} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId A unique value identifying this game session.
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionsReadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameSession}
     */
    gameEngineApiSessionsRead(sessionId, callback) {
      let postBody = null;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionsRead");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GameSession;
      return this.apiClient.callApi(
        '/game_engine_api/sessions/{session_id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the gameEngineApiSessionsUpdate operation.
     * @callback module:api/GameEngineApiApi~gameEngineApiSessionsUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameSession} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sessionId A unique value identifying this game session.
     * @param {module:model/GameSession} data 
     * @param {module:api/GameEngineApiApi~gameEngineApiSessionsUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GameSession}
     */
    gameEngineApiSessionsUpdate(sessionId, data, callback) {
      let postBody = data;
      // verify the required parameter 'sessionId' is set
      if (sessionId === undefined || sessionId === null) {
        throw new Error("Missing the required parameter 'sessionId' when calling gameEngineApiSessionsUpdate");
      }
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling gameEngineApiSessionsUpdate");
      }

      let pathParams = {
        'session_id': sessionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Basic'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GameSession;
      return this.apiClient.callApi(
        '/game_engine_api/sessions/{session_id}/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
