/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CardsAgainstHumanityDjangoApi);
  }
}(this, function(expect, CardsAgainstHumanityDjangoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GameRoundWinnerUser', function() {
    it('should create an instance of GameRoundWinnerUser', function() {
      // uncomment below and update the code to test GameRoundWinnerUser
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be.a(CardsAgainstHumanityDjangoApi.GameRoundWinnerUser);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property lastLogin (base name: "last_login")', function() {
      // uncomment below and update the code to test the property lastLogin
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property isSuperuser (base name: "is_superuser")', function() {
      // uncomment below and update the code to test the property isSuperuser
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property isStaff (base name: "is_staff")', function() {
      // uncomment below and update the code to test the property isStaff
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "is_active")', function() {
      // uncomment below and update the code to test the property isActive
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property dateJoined (base name: "date_joined")', function() {
      // uncomment below and update the code to test the property dateJoined
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property groups (base name: "groups")', function() {
      // uncomment below and update the code to test the property groups
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

    it('should have the property userPermissions (base name: "user_permissions")', function() {
      // uncomment below and update the code to test the property userPermissions
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinnerUser();
      //expect(instance).to.be();
    });

  });

}));
