/**
 * fast-cards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastCards);
  }
}(this, function(expect, FastCards) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastCards.GamePreferences();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GamePreferences', function() {
    it('should create an instance of GamePreferences', function() {
      // uncomment below and update the code to test GamePreferences
      //var instane = new FastCards.GamePreferences();
      //expect(instance).to.be.a(FastCards.GamePreferences);
    });

    it('should have the property deckPreferences (base name: "deck_preferences")', function() {
      // uncomment below and update the code to test the property deckPreferences
      //var instane = new FastCards.GamePreferences();
      //expect(instance).to.be();
    });

    it('should have the property pointsNeededForWin (base name: "points_needed_for_win")', function() {
      // uncomment below and update the code to test the property pointsNeededForWin
      //var instane = new FastCards.GamePreferences();
      //expect(instance).to.be();
    });

    it('should have the property maxRoundCount (base name: "max_round_count")', function() {
      // uncomment below and update the code to test the property maxRoundCount
      //var instane = new FastCards.GamePreferences();
      //expect(instance).to.be();
    });

  });

}));
