/**
 * CardsAgainstHumanity-Django API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CardsAgainstHumanityDjangoApi);
  }
}(this, function(expect, CardsAgainstHumanityDjangoApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CardsAgainstHumanityDjangoApi.GameRoundWinner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GameRoundWinner', function() {
    it('should create an instance of GameRoundWinner', function() {
      // uncomment below and update the code to test GameRoundWinner
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinner();
      //expect(instance).to.be.a(CardsAgainstHumanityDjangoApi.GameRoundWinner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinner();
      //expect(instance).to.be();
    });

    it('should have the property bio (base name: "bio")', function() {
      // uncomment below and update the code to test the property bio
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinner();
      //expect(instance).to.be();
    });

    it('should have the property avatar (base name: "avatar")', function() {
      // uncomment below and update the code to test the property avatar
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinner();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instane = new CardsAgainstHumanityDjangoApi.GameRoundWinner();
      //expect(instance).to.be();
    });

  });

}));
