/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SnippetsApi);
  }
}(this, function(expect, SnippetsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SnippetsApi.PasswordResetConfirm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PasswordResetConfirm', function() {
    it('should create an instance of PasswordResetConfirm', function() {
      // uncomment below and update the code to test PasswordResetConfirm
      //var instane = new SnippetsApi.PasswordResetConfirm();
      //expect(instance).to.be.a(SnippetsApi.PasswordResetConfirm);
    });

    it('should have the property newPassword1 (base name: "new_password1")', function() {
      // uncomment below and update the code to test the property newPassword1
      //var instane = new SnippetsApi.PasswordResetConfirm();
      //expect(instance).to.be();
    });

    it('should have the property newPassword2 (base name: "new_password2")', function() {
      // uncomment below and update the code to test the property newPassword2
      //var instane = new SnippetsApi.PasswordResetConfirm();
      //expect(instance).to.be();
    });

    it('should have the property uid (base name: "uid")', function() {
      // uncomment below and update the code to test the property uid
      //var instane = new SnippetsApi.PasswordResetConfirm();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instane = new SnippetsApi.PasswordResetConfirm();
      //expect(instance).to.be();
    });

  });

}));
